version: "3.7"

services:
  
  db:
    restart: always
    image: postgres:14-alpine
    env_file:
      - .env_db.prod
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432

  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 --bind 0.0.0.0:8000 app:app
    env_file:
      - .env_app.prod
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
    name: postgres_data
